name: Go Docker

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build the Docker image
        run: |
          docker build . --tag ghcr.io/${{ github.actor }}/ticktockbox:latest
          docker run ghcr.io/${{ github.actor }}/ticktockbox:latest
          docker push ghcr.io/${{ github.actor }}/ticktockbox:latest


